# Generated by Django 2.0.2 on 2018-06-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='department',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
