# Generated by Django 2.0.7 on 2018-08-08 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_introduce'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='descriptionn',
            new_name='discription',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='follow_count',
            new_name='followers_count',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='follower_count',
            new_name='friends_count',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='id',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='favourites_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='listed_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='location',
            field=models.CharField(default='japan', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='statuses_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='url',
            field=models.CharField(default='none', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='introduce',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='social_django.UserSocialAuth'),
        ),
    ]
