# Generated by Django 2.0.6 on 2018-07-16 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_introduce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introduce',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='social_django.UserSocialAuth'),
        ),
    ]
