# Generated by Django 2.0.6 on 2018-07-16 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='introduce',
            name='user',
        ),
        migrations.DeleteModel(
            name='Introduce',
        ),
    ]
